-- MySQL Script generated by MySQL Workbench
-- Sun Nov  2 12:49:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kitchen_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kitchen_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kitchen_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kitchen_db` ;

-- -----------------------------------------------------
-- Table `kitchen_db`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(100) NULL DEFAULT NULL,
  `contact_person` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `delivery_days` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`consumables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`consumables` (
  `consumable_id` INT NOT NULL AUTO_INCREMENT,
  `consumable_name` VARCHAR(50) NULL DEFAULT NULL,
  `consumable_expiration_date` DATE NULL DEFAULT NULL,
  `consumable_initial_date` DATE NULL DEFAULT NULL,
  `consumable_quantity` INT NULL DEFAULT NULL,
  `consumable_price` DECIMAL(9,2) NULL DEFAULT NULL,
  `consumable_calories` INT NULL DEFAULT NULL,
  `consumable_allergen` VARCHAR(9) NULL DEFAULT NULL,
  `supplier_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`consumable_id`),
  CONSTRAINT `fk_consumables_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `kitchen_db`.`suppliers` (`supplier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`kitchenpersonnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`kitchenpersonnel` (
  `staffid` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `staffrole` VARCHAR(50) NULL DEFAULT NULL,
  `certification` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `hiredate` DATE NULL DEFAULT NULL,
  `stationassigned` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`staffid`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`personnelcompetencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`personnelcompetencies` (
  `competencyid` INT NOT NULL AUTO_INCREMENT,
  `staffid` INT NOT NULL,
  `competencyname` VARCHAR(100) NOT NULL,
  `iscertified` TINYINT(1) NULL DEFAULT '0',
  `issueddate` DATE NULL DEFAULT NULL,
  `expirydate` DATE NULL DEFAULT NULL,
  `issuingauthority` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`competencyid`),
  CONSTRAINT `fk_competencies_staff`
    FOREIGN KEY (`staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personnelcompetencies_ibfk_1`
    FOREIGN KEY (`staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`personnelsanitationlogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`personnelsanitationlogs` (
  `logid` INT NOT NULL AUTO_INCREMENT,
  `staffid` INT NOT NULL,
  `areacleaned` VARCHAR(100) NULL DEFAULT NULL,
  `cleaningdate` DATE NULL DEFAULT NULL,
  `cleaningtime` TIME NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`logid`),
  CONSTRAINT `fk_sanitation_staff`
    FOREIGN KEY (`staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personnelsanitationlogs_ibfk_1`
    FOREIGN KEY (`staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`personnelviolations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`personnelviolations` (
  `violationid` INT NOT NULL AUTO_INCREMENT,
  `staffid` INT NOT NULL,
  `violationtype` VARCHAR(100) NULL DEFAULT NULL,
  `severitylevel` ENUM('Low', 'Moderate', 'High') NULL DEFAULT NULL,
  `description_violation_details` TEXT NULL DEFAULT NULL,
  `violationdate` DATE NOT NULL,
  `correctiveactiontaken` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`violationid`),
  CONSTRAINT `fk_violations_staff`
    FOREIGN KEY (`staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `personnelviolations_ibfk_1`
    FOREIGN KEY (`staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`recipe_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`recipe_table` (
  `Recipe_id` INT NOT NULL AUTO_INCREMENT,
  `Recipe_name` VARCHAR(83) NULL DEFAULT NULL,
  `Catagory` VARCHAR(9) NULL DEFAULT NULL,
  `created_by_staffid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Recipe_id`),
  CONSTRAINT `fk_recipe_created_by`
    FOREIGN KEY (`created_by_staffid`)
    REFERENCES `kitchen_db`.`kitchenpersonnel` (`staffid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kitchen_db`.`recipe_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchen_db`.`recipe_ingredients` (
  `recipe_ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `consumable_id` INT NOT NULL,
  `quantity` DECIMAL(10,2) NOT NULL,
  `unit` VARCHAR(20) NULL DEFAULT NULL,
  `preparation_notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`recipe_ingredient_id`),
  CONSTRAINT `fk_recipe_ingredients_consumable`
    FOREIGN KEY (`consumable_id`)
    REFERENCES `kitchen_db`.`consumables` (`consumable_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recipe_ingredients_recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `kitchen_db`.`recipe_table` (`Recipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
